version: "3.9"

server:
  port: 8080
---
springdoc:
  swagger-ui:
     enabled: true
     layout: BaseLayout
     operationsSorter: method
     path: /swagger-ui.html
  api-docs:
     path: /api-docs
---
logging:
   level:
     root: INFO
     org:
       springframework:
         web: info
---
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  data:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
---
axon:
  axonserver:
    servers: axonserver:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson